name: Selenium Test Suite
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    workflow_dispatch:
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache : maven

      - name: Run Selenium Tests
        run: cd b1_SeleniumFramework && mvn clean test -Dbrowser=chrome -Denv=dev -DsuiteXmlFile=testng.xml -Dheadless=true

      - name: Upload Test Report
      if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
        path: b1_SeleniumFramework/target/surefire-reports/
        path: b1_SeleniumFramework/target/screeshots/