name: Selenium Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Firefox
        run: sudo apt-get update && sudo apt-get install -y firefox

      - name: Run Selenium Tests
        run: |
          cd b1_SeleniumFramework
          mvn clean test \
          -Dbrowser=${{ matrix.browser }} \
          -Denv=dev \
          -Dusername=${{ secrets.TEST_USERNAME }} \
          -Dpassword=${{ secrets.TEST_PASS }} \
          -DsuiteXmlFile=testng-smoke.xml

      # ✅ Upload test results
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-result-${{ matrix.browser }}
          path: b1_SeleniumFramework/target/

      # ✅ Generate Allure
      - name: Generate Allure Report
        run: |
          cd b1_SeleniumFramework
          mvn allure:report

      # ✅ Upload Allure
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.browser }}
          path: b1_SeleniumFramework/target/site/allure-maven-plugin/